plugins:
  category_custom_field_enabled:
    default: true
    client: true
  category_custom_field_name:
    default: 'rcategoryinfo'
    client: true
  category_custom_field_type:
    default: 'json'
    client: true
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json